name: osmosis-math-tests
format: 0.1.0
validation: ./polywrap.test.cue
jobs:
  calc:
    steps:
      - uri: file/build
        method: calcPriceImpactWithAmount
        args:
          spotPriceBefore: "15345"
          tokenAmount: "53234223"
          priceImpact: "12432"
